#!/usr/bin/env python3
"""Render the catalog into the markdown pages this repository publishes.

── Why this file is shaped the way it is ────────────────────────────────────

A question bank on GitHub is read through GitHub's markdown renderer, and that
renderer has a hard limit nobody sees coming: **it stops rendering a file at
512,000 bytes** and prints a truncation notice instead of the rest. A repository
whose whole catalog is one table in one README therefore has a ceiling built
into it, and it gets slower the whole way up to that ceiling — one table of a
few thousand rows is a multi-megabyte DOM on the landing page every visitor
pays for before they have found anything.

So the shape here is the opposite one: **the README is an index, and the rows
live in shards.**

  * ``README.md`` is capped at :data:`README_MAX_BYTES` and carries navigation
    plus the newest :data:`README_LATEST_ROWS` sightings. It is the page every
    visitor loads, so it is the page that must stay small.
  * Rows live in ``companies/``, ``formats/`` and ``by-month/`` — three ways
    into the same set, each a small file. Every generated page is capped at
    :data:`PAGE_MAX_BYTES` and paginates into ``-2.md``, ``-3.md`` when it
    would not fit, so no file can grow into the truncation limit no matter how
    large the bank gets.
  * ``data/`` carries the whole set once, machine-readable, as JSONL and CSV —
    one row per line, sorted by slug, so a changed question is a one-line diff
    rather than a rewritten file. That is also what keeps the repository small
    to clone: a table sorted by DATE reorders every line whenever anything is
    added, and an hourly job that rewrites a large file hourly is a repository
    that grows without anyone adding anything.

── Rules every renderer here holds ──────────────────────────────────────────

  * **An unknown date is never printed as a date.** A question with no recorded
    sighting shows ``—``, is sorted last, is never marked fresh, and does not
    appear in ``by-month/`` at all. Falling back to the row's creation date
    would publish the day we imported a question as the day someone was asked
    it, which is a claim we cannot support.
  * **A cell is a mark, never prose.** Titles are escaped, never truncated into
    a different title.
  * **Rendering is pure and clock-injected.** ``today`` is an argument, there is
    no randomness, and the same snapshot renders byte-identically every time —
    which is what makes ``--check`` meaningful and what stops the hourly job
    committing noise.
"""

from __future__ import annotations

import csv
import io
import json
from dataclasses import dataclass
from datetime import date
from typing import Callable, Iterable, Sequence

from catalog import Question
from labels import (
    DIFFICULTY_ORDER,
    FORMAT_ORDER,
    company_key,
    company_label,
    difficulty_label,
    format_label,
)

# GitHub renders at most 512,000 bytes of a markdown file. Both caps below sit
# well under it so that a bank several times today's size still renders whole —
# the point is not to approach the limit safely, it is never to be near it.
GITHUB_RENDER_LIMIT = 512_000
README_MAX_BYTES = 96_000
PAGE_MAX_BYTES = 192_000

# How many of the newest sightings the landing page shows. Every one of them is
# a row someone might click; past this a visitor is scrolling, not reading, and
# the navigation below the table is the faster way to what they came for.
README_LATEST_ROWS = 100

# Companies named directly in the README's navigation. The rest are one click
# away in `companies/README.md`, which has no row budget to defend.
README_TOP_COMPANIES = 48

# Rows per generated page before it paginates. Chosen so a page stays a fast
# load on a phone rather than so it stays under the byte cap — the cap is the
# backstop, this is the intent.
ROWS_PER_PAGE = 250

# A sighting this recent is marked. Both windows are the reference points a
# candidate actually uses: "this cycle" and "this season".
FIRE_DAYS = 14
NEW_DAYS = 45

MONTH_NAMES = ("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

GENERATED_NOTICE = "<!-- Generated by scripts/sync.py. Do not edit by hand: the next sync overwrites it. -->"


@dataclass(frozen=True)
class RenderResult:
    """Every file the sync would write, and what it noticed while writing them."""

    files: dict[str, str]
    stats: dict[str, object]


# ── cells ────────────────────────────────────────────────────────────────────


def escape_cell(value: str) -> str:
    """Make arbitrary catalog text safe inside a markdown table cell.

    A pipe would end the cell and a bracket would start a link, so both are
    replaced with their entities — the text renders identically and the table
    survives a title nobody sanitised on the way in. Backslashes go first, or
    escaping them afterwards would double-escape what the earlier rules wrote.
    """
    return (
        value.replace("\\", "&#92;")
        .replace("|", "&#124;")
        .replace("[", "&#91;")
        .replace("]", "&#93;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def freshness_marker(reported: date | None, today: date) -> str:
    """``🔥``/``🆕``/nothing, from the SIGHTING date only.

    A question with no recorded sighting gets no marker. It is not stale — it is
    unmeasured, and the two look identical on a page only if you let them.
    """
    if reported is None:
        return ""
    age = (today - reported).days
    if age < 0:
        return ""
    if age <= FIRE_DAYS:
        return "🔥 "
    if age <= NEW_DAYS:
        return "🆕 "
    return ""


def reported_cell(question: Question, today: date) -> str:
    """The Reported column: a marked date, a month, or an honest dash."""
    if question.reported_date is None:
        return "—"
    marker = freshness_marker(question.reported_date, today)
    stamp = question.reported_date
    if question.reported_is_month_only:
        return f"{marker}{MONTH_NAMES[stamp.month - 1]} {stamp.year}"
    return f"{marker}{MONTH_NAMES[stamp.month - 1]} {stamp.day:02d}, {stamp.year}"


def _sort_key(question: Question) -> tuple:
    """Newest sighting first; undated last; ties broken so the order is total.

    A total order matters more than it looks: two questions that compared equal
    would be free to swap places between syncs, and every swap is a committed
    diff on a file nobody changed.
    """
    reported = question.reported_date
    return (
        0 if reported else 1,
        -(reported.toordinal() if reported else 0),
        -(question.added_date.toordinal() if question.added_date else 0),
        -question.number,
        question.slug,
    )


def sort_questions(questions: Iterable[Question]) -> list[Question]:
    return sorted(questions, key=_sort_key)


# ── tables ───────────────────────────────────────────────────────────────────

Column = tuple[str, str, Callable[[Question], str]]  # header, alignment, cell


def _company_cell(question: Question, api_labels: dict[str, str]) -> str:
    if not question.companies:
        return "—"
    return " / ".join(escape_cell(company_label(c, api_labels)) for c in question.companies)


def columns_for(view: str, api_labels: dict[str, str], today: date) -> list[Column]:
    """The columns a view prints.

    Each view drops the column it is already filtered by — a company page has no
    Company column — which is most of why these files are small.
    """
    company: Column = ("Company", ":--", lambda q: f"**{_company_cell(q, api_labels)}**")
    question: Column = (
        "Question",
        ":--",
        lambda q: f"[{escape_cell(q.title)}]({q.url})",
    )
    fmt: Column = ("Format", ":--", lambda q: escape_cell(format_label(q.type)))
    difficulty: Column = (
        "Difficulty",
        ":-:",
        lambda q: difficulty_label(q.difficulty) or "—",
    )
    reported: Column = ("Reported", ":--", lambda q: reported_cell(q, today))

    if view == "company":
        return [question, fmt, difficulty, reported]
    if view == "format":
        return [company, question, difficulty, reported]
    if view == "month":
        return [company, question, fmt, difficulty]
    return [company, question, fmt, difficulty, reported]


def render_table(questions: Sequence[Question], cols: Sequence[Column]) -> str:
    header = "| " + " | ".join(name for name, _, _ in cols) + " |"
    divider = "| " + " | ".join(align for _, align, _ in cols) + " |"
    rows = ["| " + " | ".join(cell(q) for _, _, cell in cols) + " |" for q in questions]
    return "\n".join([header, divider, *rows])


# ── pages ────────────────────────────────────────────────────────────────────


def _page_path(base: str, page: int) -> str:
    return f"{base}.md" if page == 1 else f"{base}-{page}.md"


def _pager(base_name: str, page: int, pages: int) -> str:
    """Prev/next links between the pages of one shard."""
    if pages <= 1:
        return ""
    links = []
    if page > 1:
        links.append(f"[← Page {page - 1}]({_page_path(base_name, page - 1).rsplit('/', 1)[-1]})")
    links.append(f"Page {page} of {pages}")
    if page < pages:
        links.append(f"[Page {page + 1} →]({_page_path(base_name, page + 1).rsplit('/', 1)[-1]})")
    return "<sub>" + " · ".join(links) + "</sub>"


def render_shard(
    *,
    base: str,
    title: str,
    lede: str,
    back: str,
    questions: Sequence[Question],
    cols: Sequence[Column],
) -> dict[str, str]:
    """One shard, paginated at :data:`ROWS_PER_PAGE`.

    Returns every page it produced. A shard that fits is exactly one file, and
    the ``-2.md`` suffix never appears for it — so a company whose count crosses
    the threshold gains a file rather than renaming the one it had.
    """
    ordered = sort_questions(questions)
    chunks = [ordered[i : i + ROWS_PER_PAGE] for i in range(0, len(ordered), ROWS_PER_PAGE)] or [[]]
    pages: dict[str, str] = {}
    for index, chunk in enumerate(chunks, start=1):
        pager = _pager(base, index, len(chunks))
        body = [
            GENERATED_NOTICE,
            "",
            f"# {title}",
            "",
            lede,
            "",
            back,
            "",
        ]
        if pager:
            body += [pager, ""]
        body += [render_table(chunk, cols), ""]
        if pager:
            body += [pager, ""]
        pages[_page_path(base, index)] = "\n".join(body)
    return pages


# ── navigation blocks (injected into README between markers) ─────────────────


def format_nav(by_format: dict[str, list[Question]]) -> str:
    parts = []
    for fmt in FORMAT_ORDER:
        rows = by_format.get(fmt)
        if not rows:
            continue
        parts.append(f"[{format_label(fmt)} ({len(rows):,})](formats/{fmt}.md)")
    for fmt in sorted(set(by_format) - set(FORMAT_ORDER)):
        parts.append(f"[{format_label(fmt)} ({len(by_format[fmt]):,})](formats/{fmt}.md)")
    return "**By format:** " + " · ".join(parts)


def company_nav(companies: Sequence[tuple[str, str, int]]) -> str:
    """The README's company row: the busiest, then a link to all of them."""
    shown = companies[:README_TOP_COMPANIES]
    parts = [f"[{escape_cell(name)} ({count})](companies/{key}.md)" for key, name, count in shown]
    line = "**By company:** " + " · ".join(parts)
    if len(companies) > len(shown):
        line += f" · [**all {len(companies)} companies →**](companies/README.md)"
    return line


def month_nav(months: Sequence[tuple[str, int]]) -> str:
    parts = [f"[{_month_label(key)} ({count})](by-month/{key}.md)" for key, count in months[:12]]
    line = "**By month:** " + " · ".join(parts)
    if len(months) > 12:
        line += f" · [**every month →**](by-month/README.md)"
    return line


def _month_label(key: str) -> str:
    year, month = key.split("-")
    return f"{MONTH_NAMES[int(month) - 1]} {year}"


def inject(document: str, marker: str, content: str) -> str:
    """Replace the block between ``<!-- marker:start -->``/``:end`` markers.

    Marker injection rather than whole-file generation, so the README's prose
    stays hand-editable and only the parts a machine owns are machine-written.
    Missing markers are an error: a silently skipped block is a stale number on
    the landing page, and nobody audits a landing page.
    """
    start, end = f"<!-- {marker}:start -->", f"<!-- {marker}:end -->"
    head, sep, rest = document.partition(start)
    if not sep:
        raise ValueError(f"README is missing the {start} marker")
    _, sep2, tail = rest.partition(end)
    if not sep2:
        raise ValueError(f"README is missing the {end} marker")
    return f"{head}{start}\n{content}\n{end}{tail}"


# ── data exports ─────────────────────────────────────────────────────────────

CSV_COLUMNS = (
    "slug", "title", "format", "difficulty", "companies", "topics", "tags",
    "rounds", "reported", "has_solution", "access_tier", "url", "added_at",
)


def _export_row(question: Question, api_labels: dict[str, str]) -> dict[str, object]:
    return {
        "slug": question.slug,
        "title": question.title,
        "format": question.type,
        "difficulty": question.difficulty,
        "companies": [company_label(c, api_labels) for c in question.companies],
        "topics": list(question.topics),
        "tags": list(question.tags),
        "rounds": list(question.rounds),
        "reported": question.reported,
        "has_solution": question.has_solution,
        "access_tier": question.access_tier,
        "url": question.url,
        "added_at": question.added_at,
    }


def render_jsonl(questions: Sequence[Question], api_labels: dict[str, str]) -> str:
    """One compact JSON object per line, sorted by slug.

    Line-per-record and slug-sorted for the same reason: a question that changes
    is one changed line, so git stores a delta instead of a new copy of the whole
    catalog every hour. A single pretty-printed array would be correct and would
    grow this repository by megabytes a week.
    """
    rows = sorted(questions, key=lambda q: q.slug)
    return "".join(
        json.dumps(_export_row(q, api_labels), ensure_ascii=False, separators=(",", ":"), sort_keys=True) + "\n"
        for q in rows
    )


def render_csv(questions: Sequence[Question], api_labels: dict[str, str]) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=CSV_COLUMNS, lineterminator="\n")
    writer.writeheader()
    for question in sorted(questions, key=lambda q: q.slug):
        row = _export_row(question, api_labels)
        for key in ("companies", "topics", "tags", "rounds"):
            row[key] = "; ".join(row[key])  # type: ignore[arg-type]
        writer.writerow(row)
    return buffer.getvalue()


def render_companies_csv(companies: Sequence[tuple[str, str, int]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(["slug", "company", "questions", "page", "site_url"])
    for key, name, count in sorted(companies, key=lambda c: c[0]):
        writer.writerow([key, name, count, f"companies/{key}.md", f"https://trueinterview.io/problems/company/{key}"])
    return buffer.getvalue()
